import React, { useState } from 'react';
import { X, MapPin, Cpu, Target, Hash } from 'lucide-react';

const DeployNodeModal = ({ isOpen, onClose, onSubmit, districts, sensors }) => {
  const [formData, setFormData] = useState({
    district_id: '',
    latitude: '',
    longitude: '',
    coverage_radius: 20
  });

  if (!isOpen) return null;

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const getAutoGeneratedId = () => {
    if (!formData.district_id) return "Select Region First";
    const selectedDistrict = districts.find(d => d.id === parseInt(formData.district_id, 10));
    if (!selectedDistrict) return "Invalid Region";

    const prefix = selectedDistrict.name.substring(0, 3).toUpperCase();
    
    // Find all sensors that start with this prefix
    const existingIds = (sensors || [])
      .filter(s => s.sensor_name && s.sensor_name.startsWith(prefix))
      .map(s => {
        const numStr = s.sensor_name.substring(3);
        return parseInt(numStr, 10);
      })
      .filter(n => !isNaN(n));

    const nextNum = existingIds.length > 0 ? Math.max(...existingIds) + 1 : 1;
    return `${prefix}${String(nextNum).padStart(3, '0')}`;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    // Convert to proper types before sending
    const payload = {
      ...formData,
      district_id: parseInt(formData.district_id, 10),
      latitude: parseFloat(formData.latitude),
      longitude: parseFloat(formData.longitude),
      coverage_radius: parseInt(formData.coverage_radius, 10)
    };
    
    onSubmit(payload);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#060b13]/80 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="w-full max-w-md bg-[#0f172a] border border-slate-700/60 shadow-[0_20px_60px_-15px_rgba(0,0,0,0.5)] rounded-2xl overflow-hidden flex flex-col relative">
        
        {/* Header */}
        <div className="flex justify-between items-center p-5 border-b border-slate-700/60 bg-[#1e293b]/50">
          <h2 className="text-lg font-extrabold text-blue-400 tracking-tight flex items-center gap-2">
            <Cpu size={18} /> Initialize Hardware Node
          </h2>
          <button 
            type="button"
            onClick={onClose}
            className="text-slate-400 hover:text-white transition-colors p-1 bg-slate-800/50 hover:bg-slate-700 rounded-md"
          >
            <X size={18} />
          </button>
        </div>

        {/* Form Content */}
        <form onSubmit={handleSubmit} className="p-6 space-y-5">
          
          <div>
            <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-1.5 flex items-center gap-1.5">
              <Hash size={12}/> Node Identity (Auto Generated)
            </label>
            <div className="w-full bg-[#1e293b]/40 border border-slate-700/50 rounded-lg px-4 py-2.5 text-blue-400 font-mono text-sm font-bold flex items-center shadow-inner cursor-not-allowed">
              {getAutoGeneratedId()}
            </div>
            <div className="text-[10px] text-slate-500 mt-1.5">Automatically tracked and serialized by backend router.</div>
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-1.5 flex items-center gap-1.5">
              <MapPin size={12}/> Region Selection (District ID)
            </label>
             <select 
              name="district_id"
              required
              value={formData.district_id}
              onChange={handleChange}
              className="w-full bg-[#1e293b]/60 border border-slate-600/50 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/50 transition-all text-sm appearance-none"
            >
              <option value="" disabled>-- Select Hub --</option>
              {districts.map(d => (
                <option key={d.id} value={d.id} className="bg-slate-900">{d.name} (ID: {d.id})</option>
              ))}
            </select>
            <div className="text-[10px] text-slate-500 mt-1.5">Nodes must be attached to an active physical district hub.</div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-1.5">Latitude</label>
              <input 
                type="number" 
                name="latitude"
                required
                step="any"
                min="-90"
                max="90"
                placeholder="18.5204"
                value={formData.latitude}
                onChange={handleChange}
                className="w-full bg-[#1e293b]/60 border border-slate-600/50 rounded-lg px-3 py-2 text-white focus:outline-none focus:border-blue-500 text-sm font-mono"
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-1.5">Longitude</label>
              <input 
                type="number" 
                name="longitude"
                required
                step="any"
                min="-180"
                max="180"
                placeholder="73.8567"
                value={formData.longitude}
                onChange={handleChange}
                className="w-full bg-[#1e293b]/60 border border-slate-600/50 rounded-lg px-3 py-2 text-white focus:outline-none focus:border-blue-500 text-sm font-mono"
              />
            </div>
          </div>

          <div>
             <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-1.5 flex items-center gap-1.5">
               <Target size={12}/> Coverage Radius (km)
             </label>
             <input 
                type="number" 
                name="coverage_radius"
                required
                min="1"
                value={formData.coverage_radius}
                onChange={handleChange}
                className="w-full bg-[#1e293b]/60 border border-slate-600/50 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-blue-500 placeholder:text-slate-600 transition-all font-mono text-sm"
              />
          </div>

          {/* Actions */}
          <div className="pt-4 flex items-center gap-3">
            <button 
              type="button" 
              onClick={onClose}
              className="flex-1 px-4 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg font-bold text-sm transition-colors"
            >
              Cancel
            </button>
            <button 
              type="submit"
              className="flex-1 px-4 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-bold text-sm transition-colors shadow-lg shadow-blue-500/20"
            >
              Deploy Node
            </button>
          </div>
          
        </form>
      </div>
    </div>
  );
};

export default DeployNodeModal;
